//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtNet.DevFw.Toolkit.NetCrawl {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebManageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebManageResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AtNet.DevFw.Toolkit.NetCrawl.WebManageResource", typeof(WebManageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;创建项目-${subtitle}&lt;/title&gt;
        ///    ${ct_css}
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///&lt;!--
        ///
        /////
        ///// Copyright 2011 @ S1N1.COM,All rights reseved.
        ///// Project : 奥博网站管理系统
        ///// Name : 采集组件
        ///// Author : Newmin (newmin.net@gmail.com)
        ///// Create : 2011/08/27 15:27
        ///// Product Link: http://www.ops.cc
        /////
        ///
        ///--&gt;
        ///
        ///${navigator}
        ///
        ///&lt;span id=&quot;msg&quot;&gt;&lt;/span&gt;
        ///	    
        ///&lt;form action=&quot;&quot; target=&quot;ct_ifr&quot; method=&quot;post&quot; enctype=&quot;application/x-www-form-urlencoded&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string create_project {
            get {
                return ResourceManager.GetString("create_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;删除项目-${subtitle}&lt;/title&gt;
        ///    ${ct_css}
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///&lt;!--
        ///
        /////
        ///// Copyright 2011 @ S1N1.COM,All rights reseved.
        ///// Project : 奥博网站管理系统
        ///// Name : 采集组件
        ///// Author : Newmin (newmin.net@gmail.com)
        ///// Create : 2011/08/27 15:27
        ///// Product Link: http://www.ops.cc
        /////
        ///
        ///--&gt;
        ///
        ///${navigator}
        ///&lt;br/&gt;
        ///&lt;div class=&quot;delete&quot;&gt;
        ///
        ///    ${msg}
        ///
        ///&lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt; 的本地化字符串。
        /// </summary>
        internal static string delete_project {
            get {
                return ResourceManager.GetString("delete_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;错误提示&lt;/title&gt;
        ///    ${ct_css}
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;!--
        ///
        /////
        ///// Copyright 2011 @ S1N1.COM,All rights reseved.
        ///// Project : 奥博网站管理系统
        ///// Name : 采集组件
        ///// Author : Newmin (newmin.net@gmail.com)
        ///// Create : 2011/08/27 15:27
        ///// Product Link: http://www.ops.cc
        /////
        ///
        ///--&gt;
        ///
        ///${navigator}&lt;br/&gt;&lt;br/&gt;
        ///${msg}
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt; 的本地化字符串。
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;开始采集-${subtitle}&lt;/title&gt;
        ///    ${ct_css}
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///&lt;!--
        ///
        /////
        ///// Copyright 2011 @ S1N1.COM,All rights reseved.
        ///// Project : 奥博网站管理系统
        ///// Name : 采集组件
        ///// Author : Newmin (newmin.net@gmail.com)
        ///// Create : 2011/08/27 15:27
        ///// Product Link: http://www.ops.cc
        /////
        ///
        ///--&gt;
        ///
        ///${navigator}
        ///
        ///&lt;br/&gt;
        ///&lt;form action=&quot;&quot; method=&quot;post&quot; target=&quot;ct_ifr&quot; enctype=&quot;application/x-www-form-urlencoded&quot;&gt;
        ///    &lt;input name=&quot;ct_t [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string invoke_collect {
            get {
                return ResourceManager.GetString("invoke_collect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;div class=&quot;navigator&quot;&gt;
        ///    &lt;a href=&quot;?action=createproject&quot;&gt;创建新项目&lt;/a&gt; |
        ///    &lt;a href=&quot;?action=list&quot;&gt;项目管理&lt;/a&gt; |
        ///    &lt;a href=&quot;?action=help&quot;&gt;使用说明&lt;/a&gt;
        ///&lt;/div&gt; 的本地化字符串。
        /// </summary>
        internal static string partial_navigator {
            get {
                return ResourceManager.GetString("partial_navigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;项目列表-${subtitle}&lt;/title&gt;
        ///    ${ct_css}
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///&lt;!--
        ///
        /////
        ///// Copyright 2011 @ S1N1.COM,All rights reseved.
        ///// Project : 奥博网站管理系统
        ///// Name : 采集组件
        ///// Author : Newmin (newmin.net@gmail.com)
        ///// Create : 2011/08/27 15:27
        ///// Product Link: http://www.ops.cc
        /////
        ///
        ///--&gt;
        ///
        ///${navigator}
        ///
        ///&lt;div id=&quot;projectlist&quot;&gt;
        ///
        ///    &lt;!--
        ///    &lt;div class=&quot;project&quot;&gt;
        ///
        ///        &lt;h2&gt;
        ///            &lt;strong&gt;项目名称：测试项目(编号：neteasy)&lt;/strong&gt;
        ///        &lt;/h2&gt;
        ///        &lt;div class=&quot;details&quot;&gt;
        ///        [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string project_list {
            get {
                return ResourceManager.GetString("project_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;测试结果&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt; 的本地化字符串。
        /// </summary>
        internal static string test_result {
            get {
                return ResourceManager.GetString("test_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;修改项目-${subtitle}&lt;/title&gt;
        ///    ${ct_css}
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///&lt;!--
        ///
        /////
        ///// Copyright 2011 @ S1N1.COM,All rights reseved.
        ///// Project : 奥博网站管理系统
        ///// Name : 采集组件
        ///// Author : Newmin (newmin.net@gmail.com)
        ///// Create : 2011/08/27 15:27
        ///// Product Link: http://www.ops.cc
        /////
        ///
        ///--&gt;
        ///
        ///${navigator}
        ///
        ///&lt;span id=&quot;msg&quot;&gt;&lt;/span&gt;
        ///	    
        ///&lt;form action=&quot;&quot; target=&quot;ct_ifr&quot; method=&quot;post&quot; enctype=&quot;application/x-www-form-urlencoded&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string update_project {
            get {
                return ResourceManager.GetString("update_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 body {
        ///    font-size: 12px;
        ///    color: #666;
        ///    font-family: arail, sans-serif;
        ///}
        ///
        ///p {
        ///    text-indent: 2em;
        ///    margin: 0;
        ///    padding: 5px 0;
        ///}
        ///
        ///a { color: #0066cc; }
        ///
        ///a:hover { color: #006699; }
        ///
        ///input, textarea, select { border: solid 1px #e5e5e5; }
        ///
        ///input.button {
        ///    border: outset 1px #e5e5e5;
        ///    margin-right: 5px;
        ///    color: #666;
        ///    padding: 0 8px;
        ///}
        ///
        ///span.txt {
        ///    float: left;
        ///    padding-right: 10px;
        ///}
        ///
        ///div.project_operate {
        ///    text-align: right;
        ///    padding-r [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string webmanagestyle {
            get {
                return ResourceManager.GetString("webmanagestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;欢迎使用asp.net采集插件&lt;/title&gt;
        ///    ${ct_css}
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///&lt;!--
        ///
        /////
        ///// Copyright 2011 @ S1N1.COM,All rights reseved.
        ///// Project : 奥博网站管理系统
        ///// Name : 采集组件
        ///// Author : Newmin (newmin.net@gmail.com)
        ///// Create : 2011/08/27 15:27
        ///// Product Link: http://www.ops.cc
        /////
        ///
        ///--&gt;
        ///
        ///${navigator}
        ///&lt;p&gt;
        ///    欢迎您使用这款asp.net采集组件，本组件由奥博科技(&lt;a href=&quot;http://www.ops.cc&quot; target=&quot;_blank&quot;&gt;www.ops.cc&lt;/a&gt;)开发！&lt;br/&gt;
        ///    如您在使用过程中遇到任何问题，或您对这款产品由好的建议，欢迎上我们网站反馈！谢谢！
        ///&lt;/p&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt; 的本地化字符串。
        /// </summary>
        internal static string welcome_page {
            get {
                return ResourceManager.GetString("welcome_page", resourceCulture);
            }
        }
    }
}
