//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace J6.DevFw.Toolkit.Region {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegionRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegionRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("J6.DevFw.Toolkit.Region.RegionRes", typeof(RegionRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;items&gt;
        ///  &lt;item id=&quot;1&quot; name=&quot;北京市&quot; pid=&quot;1&quot; zip=&quot;100000&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;2&quot; name=&quot;天津市&quot; pid=&quot;2&quot; zip=&quot;100000&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;3&quot; name=&quot;石家庄市&quot; pid=&quot;3&quot; zip=&quot;050000&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;4&quot; name=&quot;唐山市&quot; pid=&quot;3&quot; zip=&quot;063000&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;5&quot; name=&quot;秦皇岛市&quot; pid=&quot;3&quot; zip=&quot;066000&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;6&quot; name=&quot;邯郸市&quot; pid=&quot;3&quot; zip=&quot;056000&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;7&quot; name=&quot;邢台市&quot; pid=&quot;3&quot; zip=&quot;054000&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;8&quot; name=&quot;保定市&quot; pid=&quot;3&quot; zip=&quot;071000&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;9 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string cities {
            get {
                return ResourceManager.GetString("cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;items&gt;
        ///  &lt;item id=&quot;1&quot; name=&quot;东城区&quot; cid=&quot;1&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;2&quot; name=&quot;西城区&quot; cid=&quot;1&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;3&quot; name=&quot;崇文区&quot; cid=&quot;1&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;4&quot; name=&quot;宣武区&quot; cid=&quot;1&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;5&quot; name=&quot;朝阳区&quot; cid=&quot;1&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;6&quot; name=&quot;丰台区&quot; cid=&quot;1&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;7&quot; name=&quot;石景山区&quot; cid=&quot;1&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;8&quot; name=&quot;海淀区&quot; cid=&quot;1&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;9&quot; name=&quot;门头沟区&quot; cid=&quot;1&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;10&quot; name=&quot;房山区&quot; cid=&quot;1&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;11&quot; name=&quot;通州区&quot; cid [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string districts {
            get {
                return ResourceManager.GetString("districts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USE [DBCT_Dev]
        ///GO
        ///IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[S_Province]&apos;) AND type in (N&apos;U&apos;))
        ///BEGIN
        ///CREATE TABLE [dbo].[S_Province](
        ///	[ProvinceID] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[ProvinceName] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        ///	[DateCreated] [datetime] NULL,
        ///	[DateUpdated] [datetime] NULL,
        /// CONSTRAINT [PK_S_Province] PRIMARY KEY CLUSTERED 
        ///(
        ///	[ProvinceID] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OF [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string pcd_AllData_V1 {
            get {
                return ResourceManager.GetString("pcd_AllData_V1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;items&gt;
        ///  &lt;item id=&quot;1&quot; name=&quot;北京市&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;2&quot; name=&quot;天津市&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;3&quot; name=&quot;河北省&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;4&quot; name=&quot;山西省&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;5&quot; name=&quot;内蒙古自治区&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;6&quot; name=&quot;辽宁省&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;7&quot; name=&quot;吉林省&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;8&quot; name=&quot;黑龙江省&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;9&quot; name=&quot;上海市&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;10&quot; name=&quot;江苏省&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;11&quot; name=&quot;浙江省&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;12&quot; name=&quot;安徽省&quot;&gt;&lt;/item&gt;
        ///  &lt;item id=&quot;13&quot; name=&quot;福建省&quot;&gt;&lt;/item&gt;
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string provinces {
            get {
                return ResourceManager.GetString("provinces", resourceCulture);
            }
        }
    }
}
